export const DROPDOWN_ACTIVE = "DROPDOWN_ACTIVE";
export const DROPDOWN_INACTIVE = "DROPDOWN_INACTIVE";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDADE_CATEGORY = "UPDADE_CATEGORY";
export const UPDADE_PRODUCTS = "UPDADE_PRODUCTS";
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REM_PRODUCT = "CART_REM_PRODUCT";
